import asyncio
import aiohttp
import re
import csv
import json
from urllib.parse import urljoin, urlparse
from bs4 import BeautifulSoup
from typing import Set, List, Dict, Optional
import time
import logging
from dataclasses import dataclass, asdict

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


@dataclass
class EmailResult:
    url: str
    emails: List[str]
    status: str
    error: Optional[str] = None
    response_time: Optional[float] = None


class SmartEmailScraper:
    def __init__(self, max_concurrent=10, timeout=30, delay_between_requests=1):
        self.max_concurrent = max_concurrent
        self.timeout = timeout
        self.delay_between_requests = delay_between_requests
        self.email_pattern = re.compile(
            r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
        )
        self.session = None
        self.semaphore = asyncio.Semaphore(max_concurrent)

    async def __aenter__(self):
        connector = aiohttp.TCPConnector(limit=100, limit_per_host=10)
        timeout = aiohttp.ClientTimeout(total=self.timeout)
        self.session = aiohttp.ClientSession(
            connector=connector,
            timeout=timeout,
            headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
            },
        )
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.session:
            await self.session.close()

    def extract_emails_from_text(self, text: str) -> Set[str]:
        """Extract email addresses from text using regex."""
        emails = set(self.email_pattern.findall(text))
        # Filter out common false positives
        filtered_emails = set()
        for email in emails:
            if not any(
                skip in email.lower()
                for skip in ["example.com", "test.com", "placeholder", "dummy"]
            ):
                filtered_emails.add(email.lower())
        return filtered_emails

    def extract_emails_from_html(self, html: str) -> Set[str]:
        """Extract emails from HTML content including mailto links."""
        emails = set()

        try:
            soup = BeautifulSoup(html, "html.parser")

            # Remove script and style elements
            for script in soup(["script", "style"]):
                script.decompose()

            # Get text content
            text = soup.get_text()
            emails.update(self.extract_emails_from_text(text))

            # Extract from mailto links
            mailto_links = soup.find_all("a", href=re.compile(r"^mailto:", re.I))
            for link in mailto_links:
                href = link.get("href", "")
                if href.startswith("mailto:"):
                    email = href[7:].split("?")[0]  # Remove mailto: and query params
                    if self.email_pattern.match(email):
                        emails.add(email.lower())

            # Extract from data attributes and hidden inputs
            for elem in soup.find_all(attrs={"data-email": True}):
                email = elem.get("data-email", "")
                if self.email_pattern.match(email):
                    emails.add(email.lower())

        except Exception as e:
            logger.warning(f"Error parsing HTML: {e}")
            # Fallback to text extraction
            emails.update(self.extract_emails_from_text(html))

        return emails

    async def scrape_single_url(self, url: str) -> EmailResult:
        """Scrape emails from a single URL."""
        async with self.semaphore:
            start_time = time.time()

            try:
                # Ensure URL has a scheme
                if not url.startswith(("http://", "https://")):
                    url = "https://" + url

                logger.info(f"Scraping: {url}")

                async with self.session.get(url, allow_redirects=True) as response:
                    if response.status == 200:
                        content = await response.text()
                        emails = list(self.extract_emails_from_html(content))
                        response_time = time.time() - start_time

                        result = EmailResult(
                            url=url,
                            emails=emails,
                            status="success",
                            response_time=response_time,
                        )

                        logger.info(f"Found {len(emails)} emails from {url}")
                        return result
                    else:
                        return EmailResult(
                            url=url,
                            emails=[],
                            status="error",
                            error=f"HTTP {response.status}",
                            response_time=time.time() - start_time,
                        )

            except asyncio.TimeoutError:
                return EmailResult(
                    url=url,
                    emails=[],
                    status="timeout",
                    error="Request timeout",
                    response_time=time.time() - start_time,
                )
            except Exception as e:
                return EmailResult(
                    url=url,
                    emails=[],
                    status="error",
                    error=str(e),
                    response_time=time.time() - start_time,
                )
            finally:
                # Add delay between requests to be respectful
                if self.delay_between_requests > 0:
                    await asyncio.sleep(self.delay_between_requests)

    async def scrape_urls(self, urls: List[str]) -> List[EmailResult]:
        """Scrape emails from multiple URLs in parallel."""
        logger.info(
            f"Starting to scrape {len(urls)} URLs with {self.max_concurrent} concurrent connections"
        )

        tasks = [self.scrape_single_url(url) for url in urls]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Handle any exceptions that occurred
        processed_results = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                processed_results.append(
                    EmailResult(
                        url=urls[i], emails=[], status="error", error=str(result)
                    )
                )
            else:
                processed_results.append(result)

        return processed_results

    def save_results_to_csv(
        self, results: List[EmailResult], filename: str = "scraped_emails.csv"
    ):
        """Save results to CSV file."""
        with open(filename, "w", newline="", encoding="utf-8") as csvfile:
            fieldnames = [
                "url",
                "status",
                "emails_found",
                "emails",
                "response_time",
                "error",
            ]
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

            writer.writeheader()
            for result in results:
                writer.writerow(
                    {
                        "url": result.url,
                        "status": result.status,
                        "emails_found": len(result.emails),
                        "emails": "; ".join(result.emails),
                        "response_time": result.response_time,
                        "error": result.error,
                    }
                )

        logger.info(f"Results saved to {filename}")

    def save_results_to_json(
        self, results: List[EmailResult], filename: str = "scraped_emails.json"
    ):
        """Save results to JSON file."""
        with open(filename, "w", encoding="utf-8") as jsonfile:
            json.dump(
                [asdict(result) for result in results],
                jsonfile,
                indent=2,
                ensure_ascii=False,
            )

        logger.info(f"Results saved to {filename}")

    def print_summary(self, results: List[EmailResult]):
        """Print a summary of the scraping results."""
        total_urls = len(results)
        successful = sum(1 for r in results if r.status == "success")
        total_emails = sum(len(r.emails) for r in results)
        unique_emails = len(set(email for r in results for email in r.emails))

        print("\n" + "=" * 50)
        print("SCRAPING SUMMARY")
        print("=" * 50)
        print(f"Total URLs processed: {total_urls}")
        print(f"Successful requests: {successful}")
        print(f"Failed requests: {total_urls - successful}")
        print(f"Total emails found: {total_emails}")
        print(f"Unique emails found: {unique_emails}")
        print(
            f"Average emails per successful URL: {total_emails/successful if successful > 0 else 0:.2f}"
        )

        if unique_emails > 0:
            print(f"\nAll unique emails found:")
            all_emails = set(email for r in results for email in r.emails)
            for email in sorted(all_emails):
                print(f"  - {email}")


async def main():
    """Example usage of the email scraper."""

    # Example URLs to scrape
    urls = [
        "atmiyasurgical.com",
        "wishingoats.com",
        "maajisafashion.com",
        "beardo.in",
        "blackpoisontattoos.com",
        "indianclothstore.com",
        "yatradham.org",
        "outdoors91.com",
        "freakins.com",
        "reneecosmetics.in",
        "bummer.in",
        "ibacosmetics.com",
        "jadeblue.com",
        "vasantmasala.com",
        "houseofmg.com",
        "aglasiangranito.com",
        "royaletouche.com",
        "okhai.org",
        "jewelegance.com",
        "gaatha.com",
        "dermatouch.com",
        "mybageecha.com",
        "athflex.com",
        "villain.in",
        "astralpipes.com",
        "unipath.in",
        "silverstore.in",
        "allgoodscents.com",
        "nuutjob.com",
        "mortantra.com",
        "justdogsstore.com",
        "toycra.com",
        "elanstore.in",
        "sunrom.com",
        "ambujagroup.com",
        "archerindia.com",
        "corseca.in",
        "rajwadu.com",
        "monarch-innovation.com",
        "saathipads.com",
        "gaatha.org",
        "urbanspacestore.in",
        "ahamjewellery.com",
        "arcedior.com",
        "sourceitright.com",
        "perfumery.co.in",
        "amounee.com",
        "nutrabox.in",
        "ebizfiling.com",
        "gabbarfarms.com",
        "gujaratgoldcentre.com",
        "menstrupedia.com",
        "veirdo.in",
        "brillare.co.in",
        "maishalifestyle.com",
        "sareez.com",
        "shreehari.co",
        "robokits.co.in",
        "ultracarepro.in",
        "kandoisweets.com",
        "syndelltech.com",
        "buytea.com",
        "fitandflex.in",
        "cellspare.com",
        "synzeal.com",
        "cake2homes.com",
        "triumph-sports.com",
        "dermalogica.in",
        "wottagirl.com",
        "ador.health",
        "bluebuddha.co.in",
        "eclatofficial.com",
        "ramdevstore.com",
        "ciceroni.in",
        "shoproom.in",
        "truerevo.com",
        "patangdori.com",
        "rewyndsnacks.com",
        "laxmiflourmill.com",
        "freemen.in",
        "theroots.in",
        "skybluestationerymart.com",
        "manektech.com",
        "fujiiryoki.in",
        "indiantradebird.com",
        "gfebusiness.org",
        "ecoright.com",
        "sweetdreams.in",
        "chhapa.in",
        "bloomsvilla.com",
        "hamercop.com",
        "hairdramacompany.com",
        "gokulgroup.com",
        "azafran.in",
        "layerr.com",
        "protectorfiresafety.com",
        "giftoo.in",
        "babli.in",
        "gambol.in",
        "bakeri.com",
        "atira.in",
        "thekurtacompany.com",
        "barebody.in",
        "houseofmarigold.com",
        "navbharatonline.com",
        "micromill.in",
        "jayhindsweets.com",
        "brantashop.com",
        "healthvit.com",
        "gushbeauty.com",
        "morphewconcept.myshopify.com",
        "ahmedabadfish.com",
        "vibewithmoi.in",
        "ahistatea.com",
        "janvicosmetic.com",
        "deepujpharmamachinery.com",
        "advinurology.com",
        "offikart.com",
        "bluecraftagro.com",
        "a4ahmedabad.com",
        "omdataentryindia.com",
        "tilla.in",
        "mangalamdesigner.com",
        "halfticket.co.in",
        "alpinefibc.com",
        "santva.com",
        "mittilifestyle.com",
        "osmfmouthopeningkit.com",
        "bhagwatipharma.co.in",
        "thecaseflick.in",
        "zplusevents.in",
        "geminatecs.com",
        "ahmedabadonlineflorists.com",
        "pavimentofloors.com",
        "tailorspoint.com",
        "studiovirtues.com",
        "brownfolds.com",
        "yourdesignerwear.com",
        "suvarnakala.com",
        "gajjarfurniture.com",
        "ashram.org",
        "phoenixhospital.in",
        "khestextiles.com",
        "webchanakya.com",
        "loopearplugs.in",
        "bhagwatipharma.in",
        "vipuldudhiyasweets.com",
        "jskplast.com",
        "fashionfloorindia.com",
        "woweye.in",
        "gujaratinfotech.com",
        "protouchskin.com",
        "divinetreeindia.com",
        "softwaresuggest.com",
        "aalap.com",
        "ecsenvironment.com",
        "thephrase.in",
        "themapstores.com",
        "aurusjewels.in",
        "upsilonofficial.com",
        "herbtib.com",
        "bassinoimpex.com",
        "roastea.online",
        "kabhi-b.com",
        "raasleela.co.in",
        "devraajgroup.com",
        "honeyveda.in",
        "cloudbuzz.in",
        "thewastore.com",
        "svitch.bike",
        "promptpestcontrol.com",
        "silaistudio.com",
        "trycone.com",
        "ashramestore.com",
        "united18.com",
        "wehear.in",
        "kadamcolors.com",
        "heilenbiopharm.shop",
        "mithaiandmore.in",
        "cleantechwater.co.in",
        "buysupplies.in",
        "ebooks-32.myshopify.com",
        "adultemojis.com",
        "banjaraindia.com",
        "cafeuppercrust.com",
        "sunrobotics.in",
        "tintbox.in",
        "vrajbhoomi.in",
        "prosperitymirra.com",
        "theheritageart.com",
        "papayacare.com",
        "diamond-lovers.com",
        "pavilionelectronics.com",
        "gitamediquip.com",
        "divinecasa.com",
        "pluscurvves.com",
        "coffeeworkz.com",
        "keyzone.in",
        "whiskers.in",
        "uteshiyamedicare.com",
        "abirspace.com",
        "pavits.com",
        "buyblynk.com",
        "sindhoipatola.in",
        "crmjetty.com",
        "reynaturals.com",
        "kaushikengineeringworks.com",
        "bablakites.com",
        "innersense.co.in",
        "prannuts.com",
        "onecentreindia.com",
        "hustlezy.com",
        "earthorigin.in",
        "chocoliz.com",
        "maheejaipur.com",
        "shoonyaakar.com",
        "babymoon.co.in",
        "auritabikes.com",
        "joyspoon.in",
        "parajorganics.com",
        "storyofindia.in",
        "allayurvedic.in",
        "smileinhour.com",
        "delwishealthcare.com",
        "geo-fresh.com",
        "toskachocolates.com",
        "woodenartstudio.com",
        "cubithealthcare.net",
        "pintoogarments.com",
        "pornemojis.com",
        "gogstbill.com",
        "estuaryworld.com",
        "goblinindia.com",
        "aavadinstrument.com",
        "khadivedaonline.com",
        "evzon.in",
        "risehydroponics.in",
        "karkhanawala.in",
        "yelowsoft.com",
        "kritinova.in",
        "mapinpub.com",
        "rrsheth.com",
        "heeyapediatricdental.com",
        "booksforyou.co.in",
        "evital.in",
        "umaengineers.com",
        "poojakoshticlothing.com",
        "4allbiz.in",
        "gutbasket.com",
        "cslifestyle.in",
        "hpbl.in",
        "energyshield.in",
        "thekettlery.in",
        "ratnasteeltech.com",
        "mosaicdesigns.in",
        "healthmantraspa.com",
        "bellezoe.com",
        "essentialplugin.com",
        "themeselection.com",
        "gonaturel.in",
        "wrappixel.com",
        "primejigar.com",
        "chemicals4construction.com",
        "auraherbal.in",
        "imcproduct.com",
        "amerozon.com",
        "uncutjewelry.com",
        "meghmalhaar.com",
        "eindustries.in",
        "studio156.in",
        "cushion-pillow.com",
        "toytoys.in",
        "gononsense.in",
        "kianafashion.in",
        "nessa.in",
        "dotto-objects.com",
        "seasaltcafe.in",
        "payal-houseoffashion.com",
        "aflairza.com",
        "sonatraders.international",
        "innodel.com",
        "lapinkfashion.co.in",
        "vatsaltechnosoft.com",
        "sjjadia.com",
        "apicalreform.com",
        "curlin.in",
        "zookeeper.store",
        "axistechnolabs.com",
        "nutribudfoods.com",
        "buy91.com",
        "tempnote.com",
        "orthoimplantsindia.com",
        "sensinova.in",
        "shoppingekart.com",
        "vignette.co.in",
        "cortinaindia.com",
        "spatz.in",
        "favouriteauto.com",
        "mafatlalonline.com",
        "maniartyre.com",
        "thestempedia.com",
        "nutralike.com",
        "siddheshchauhan.com",
        "pairpatola.com",
        "mrkooldrink.com",
        "rforrabbit.com",
        "infotronicx.com",
        "khalids-2.myshopify.com",
        "acnextopical.com",
        "webplanex.com",
        "araayeh.com",
        "otrix.in",
        "saree.com",
        "aranyapurefood.com",
        "sambarcafe.com",
        "trooinbound.com",
        "snan.co.in",
        "magnificoresins.com",
        "milkmor.com",
        "kzari.net",
        "cggcosmetics.com",
        "dial4tyre.com",
        "ktein.com",
        "108knots.com",
        "symphonyfabrics.in",
        "hemvini.com",
        "allayurved.com",
        "peppyocean.com",
        "bearingtoolscentre.com",
        "konnectme.video",
        "kmkassociatesllp.com",
        "calyxprofessional.com",
        "laxmiopticians.com",
        "rdcosmetics.in",
        "hetalshomemade.com",
        "happyhealthzone.com",
        "worldofcrow.in",
        "kashmiriyatstore.com",
        "cyahi.com",
        "vantagekart.com",
        "osestudios.in",
        "rapidradio.co.in",
        "davesnoni.com",
        "jumboo.in",
        "mascotevent.com",
        "flowerscakesonline.com",
        "genipsclothing.com",
        "rudrra.com",
        "smallidea.in",
        "mohitmangal.com",
        "meirajewellery.com",
        "labelaesthetics.com",
        "asianbariatrics.com",
        "nautanky.com",
        "electrobotic.in",
        "inos.in",
        "twasa.com",
        "naturetherapy.co.in",
        "teaology.in",
        "excelonip.com",
        "catsandbows.com",
        "vedlakshana.com",
        "mgviplounge.com",
        "praxinfo.com",
        "ksquareenergy.com",
        "iloveunloc.com",
        "vsshop.in",
        "impoda.com",
        "aalapservices.com",
        "ssqllp.com",
        "shatpratishat.com",
        "jaamsoroyals.in",
        "rhizome.design",
        "browseinfo.com",
        "ahmedabadtrunk.in",
        "sohamdave.com",
        "ssegpl.com",
        "whitelotuscorporation.com",
        "rawpharmabiz.com",
        "tidyprint.in",
        "greenfibre.com",
        "terrafood.co.in",
        "niceg.com",
        "puretemptation.com",
        "myprosportnutrition.com",
        "pcbworldtech.com",
        "adheera.in",
        "wonderize.in",
        "harkoistudio.com",
        "vedicfashion.com",
        "samstoy.in",
        "aditibhatt.com",
        "metroweddingcards.com",
        "flowbizexports.com",
        "trollbeads.in",
        "conflictorium.org",
        "theindustrialshop.com",
        "foodsupplementshop.in",
        "colorhunt.in",
        "dataempires.com",
        "consolegarage.com",
        "chambrayandco.in",
        "bionicsremedies.in",
        "htpgemstones.com",
        "hivagi.in",
        "silkkaftans.com",
        "artdomindia.com",
        "therootdeep.com",
        "newrameshkirana.com",
        "inezeofficial.com",
        "studiobhavikshah.com",
        "parfumlab.in",
        "91ayurveda.com",
        "11zeros.com",
        "korebi.coffee",
        "tyrehub.com",
        "rushijewels.com",
        "deltahome.in",
        "redicinemedsol.com",
        "auromin.in",
        "turquoisethestore.com",
        "gavyamart.in",
        "shareatfoods.com",
        "bizpressions.in",
        "indianwealthmanagement.in",
        "kidstudio.in",
        "swagtron.in",
        "falgunigruhudhyog.in",
        "chiccemhealthcare.in",
        "penguinengineering.in",
        "polkatots.in",
        "thewanderink.com",
        "manjulapoojashroff.com",
        "launchcarscanner.in",
        "sharpexindia.com",
        "bpaindia.org",
        "creamart.co.in",
        "indiabungy.com",
        "pahadilocal.com",
        "reflectionplanet.com",
        "magedelight.com",
        "gsfa.in",
        "wildtree.co.in",
        "purvidoshi.com",
        "jaindairy.com",
        "colourchangingpigment.com",
        "sharbatwala.in",
        "getoncrm.com",
        "babyorgano.com",
        "thetruetherapy.com",
        "khanaparcel.co.in",
        "jilmil.co.in",
        "mywelme.com",
        "godhulionlinestore.com",
        "saubhagyam.com",
        "healthygrabz.com",
        "bankjobsnearme.com",
        "coronetkitchens.com",
        "toolskit.com",
        "yunaxtech.com",
        "liverpool.co.in",
        "dolphincom.in",
        "tiedroots.com",
        "eliteevince.com",
        "matrixmeditec.com",
        "hexaplastindia.com",
        "edugoabroad.com",
        "jalelectricals.com",
        "shopbaka.com",
        "devalstore.in",
        "aanij.com",
        "asprius.in",
        "spectalook.com",
        "thalasiknitfab.com",
        "aspiresquare.com",
        "smiloshine.com",
        "shoporeva.com",
        "anayat.in",
        "miracleaccountingsoftware.com",
        "sharpex.com",
        "pujashahs.com",
        "surpriseforu.com",
        "candidroot.com",
        "abirabybeena.com",
        "pauze.in",
        "karnam.in",
        "kidsage.in",
        "terraocean.in",
        "thebeautyco.in",
        "eclatsuperior.com",
        "mobile-app-development-india.com",
        "yaanman.in",
        "theleatherworks.in",
        "epcindia.org",
        "mycareindia.co.in",
        "chavdafootcare.com",
        "orthojoy.in",
        "manyaimpex.com",
        "equiivalence.com",
        "rodzen.in",
        "abplushospital.com",
        "abhyudaybharatfamilystore.com",
        "scrapingexpert.com",
        "cocoadrama.co.in",
        "dmsretail.in",
        "waterseal.in",
        "eaglefootwears.com",
        "themoonstore.in",
        "aksoftwares.in",
        "enerlyf.com",
        "sundyotalifecare.com",
        "samptelenergy.com",
        "sonyafoods.com",
        "bomaachi.com",
        "bardi.shop",
        "bevdaas.com",
        "deshprem.co.in",
        "locallive.in",
        "modaman.in",
        "blanck.in",
        "panoramicinfotech.com",
        "zumart.in",
        "labelsugar.com",
        "heybuyers.in",
        "steptsl.com",
        "thefranchiseinsiider.com",
        "rakhistores.com",
        "higreen.in",
        "clayventures.in",
        "americancrew.in",
        "freshaler.com",
        "ganeshmobilegalaxy.in",
        "blinkkfootwear.com",
        "keralapackages.net",
        "themenslab.in",
        "doctorbulao.com",
        "glamzei.com",
        "shreehari.in",
        "kaushalendra.in",
        "hairwala.com",
        "bharatgunani-myshopify-com-2.myshopify.com",
        "sanskrutihandicrafts.com",
        "craftcanvas.com",
        "seesowkids.com",
        "radiplex.in",
        "labelratan.com",
        "nuvae.in",
        "bazukiperfumes.com",
        "ripoff.co.in",
        "auto-rickshaw.com",
        "satyanamsoft.com",
        "rajshahdesigns.com",
        "ancientrootsindia.com",
        "swastikplacement.in",
        "faymeengineering.com",
        "techultrasolutions.com",
        "ambicam.com",
        "tealab.in",
        "oildok.com",
        "futuristicclimatecontrols.in",
        "kitchentherapy.in",
        "bejandaruwalla.com",
        "rajendra.co",
        "lssports.in",
        "sugarlesslife.in",
        "scentedelic.com",
        "zestardshop.com",
        "sunohstudio.com",
        "adityabhavsar.com",
        "lawvaccine.in",
        "panilafashion.com",
        "zaurafinejewels.com",
        "nilkanthinfotech.co.in",
        "nexgits.com",
        "thehybridgreentea.com",
        "lemonlords.com",
        "charme.life",
        "romanonx.com",
        "forherstores.com",
        "joyousbeamcandles.com",
        "studiodecorai.com",
        "stanfoxes.com",
        "satyamevinfotech.com",
        "neelititlee.com",
        "aelinindia.com",
        "evairofficial.com",
        "bongoniketan.in",
        "silverlifegym.in",
        "101hues.com",
        "iriscosmetics.biz",
        "permagardindia.com",
        "thecrio.com",
        "littlepumpkin.in",
        "cruisemaxsports.com",
        "itechnotion.com",
        "craftystyles.com",
        "unione.co.in",
        "nclcpublishingblueprint.com",
        "mysofacleaning.com",
        "nikitavishakha.com",
        "shreechamundaindustries.com",
        "7decore.com",
        "mcdodo.online",
        "sashays.co.in",
        "funkydevelopers.com",
        "wovenconversion.com",
        "theappideas.com",
        "playqid.com",
        "smeltt.com",
        "falafelexpress.in",
        "sturdybikes.in",
        "gurumetachem.com",
        "tantu.co.in",
        "msafiri.in",
        "loopandknot.in",
        "brownbazaar.com",
        "tatsa.in",
        "58miles.com",
        "ecodesoft.com",
        "innopitch.in",
        "smartsyncservices.com",
        "womendata.in",
        "mybesttrip.in",
        "drasintrisk.com",
        "drivingcomfort.in",
        "aareeaccessories.com",
        "doobidoo.in",
        "perfumery.ae",
        "tibetansweatermarketahmedabad.com",
        "paratrooper.in",
        "myjik.com",
        "sweetmoon.in",
        "cheapcodesign.com",
        "luckfogic.com",
        "babajibook.com",
        "sparsh-technologies.com",
        "ultrapop.co",
        "emkayfoodproducts.com",
        "pdmed.in",
        "orangeidea.in",
        "vibidsoft.com",
        "gujjutours.com",
        "prabhuprasad.in",
        "buildmartmarketing.com",
        "dngwebtech.com",
        "fabnic.com",
        "rollyspharma.com",
        "nrvortho.com",
        "royalpiston.in",
        "kaushalam.com",
        "oetacumen.com",
        "ciccio.in",
        "tussah.in",
        "kavyastyleplus.com",
        "cisindus.org",
        "elauxy.com",
        "shahfragrances.com",
        "unoaroma.in",
        "mtechies.in",
        "itmattersindia.com",
        "gurucorporation.in",
        "travelplaza.biz",
        "earthtatva.com",
        "laxminamkeen.com",
        "webwana.com",
        "lebonheurthebliss.com",
        "shivnext.com",
        "tinymighty.in",
        "happycarts.in",
        "nirasceramics.com",
        "3dpraxisstudio.com",
        "bhagawatimach.com",
        "fairybellskart.com",
        "bhagwatimfgco.com",
        "ambahandicrafts.com",
        "ssccontrol.com",
        "jassidihatti.com",
        "giftlift.in",
        "vegavaan.com",
        "harshvijayexim.com",
        "fullmoonglobal.com",
        "printwala.com",
        "mallofsalon.com",
        "self-cntrd.in",
        "orafa.in",
        "vegetablestore-2.myshopify.com",
        "kansyammetalex.com",
        "healthnwellness.shop",
        "piccolomosaic.in",
        "kollatrr.com",
        "raigoceramica.com",
        "bloomingwellness.in",
        "jjoshi.life",
        "ibusinessmotivation.com",
        "klairestudio.shop",
        "initiotechmedia.com",
        "mollismoons.com",
        "a2shaktigir.com",
        "skinsy.in",
        "biotrexnutritions.com",
        "riyaasat.in",
        "talesandstories.com",
        "thebetagirl.in",
        "shayonastore.com",
        "skystartools.com",
        "arvybyrahulvyas.com",
        "thepaperarkstore.com",
        "firkiwala.in",
        "kanidhakhakhra.com",
        "olixir.in",
        "medoraindia.com",
        "dyelogue.com",
        "amberstitch.com",
        "indihues.com",
        "priyapumpind.com",
        "progns.com",
        "bindiindia.com",
        "amratpal.com",
        "zebeinindia.com",
        "royalbharat.com",
        "thelittlebigstore.com",
        "studionexx.com",
        "torccofficial.com",
        "garazone.com",
        "nuraliflora.com",
        "mesmerro.com",
        "giftcentre.co.in",
        "conceptfi.in",
        "prabhudasjewellers.com",
        "kishansavaliya.com",
        "brandnifty.com",
        "goadsindia.com",
        "sarausi.com",
        "kingofdmc.in",
        "clickabooks.com",
        "bulkymarketing.com",
        "meghz.com",
        "arisaa.com",
        "vishalroadlines.co.in",
        "radheflutes.com",
        "wepdemo6.myshopify.com",
        "verixhinges.com",
        "ebisutech.com",
        "neonsecret.co",
        "jamun-medical.co.in",
        "macademicsolutions.com",
        "wooum.com",
        "massagechairs.co.in",
        "dolphinwebsolution.com",
        "maulinpandya.com",
        "craftnfashion.in",
        "archoo.in",
        "volvoautobots.com",
        "anjanase.com",
        "tripstor.com",
        "dmgml9qd9iax4.cloudfront.net",
        "justsnatch.com",
        "bizople.com",
        "tandjjewelhouse.com",
        "sonicsky.shop",
        "wehearglobal.com",
        "marceltherapy.com",
        "lionvisionits.com",
        "shehridhaga.in",
        "bookbazaar.com",
        "f2fmart.com",
        "poojakeyur.in",
        "cynoinfotech.com",
        "mymeerastore.com",
        "bdhbearings.in",
        "moreoften.in",
        "everhype.in",
        "cloudrevels.com",
        "thecreationlamis.com",
        "thedotstore.com",
        "crafthues.co.in",
        "gelid.in",
        "capsule.co.in",
        "atozautopartsindia.com",
        "printahmedabad.com",
        "aswaforce.com",
        "ohwomaniyaa.in",
        "dharashahstudio.com",
        "letsannounce.com",
        "ambitionoverseas.com",
        "flyworldindia.com",
        "prishaillumination.com",
        "srashtasoft.com",
        "10xexport.com",
        "farmseindia.com",
        "savariya.in",
        "zanzibarliving.in",
        "jslathetools.com",
        "motionink.in",
        "krishascrafthub.com",
        "solid1972.com",
        "buyspaworld.com",
        "xcetra.in",
        "parfumlab.co.in",
        "allayurvedics.com",
        "ibhi.co.in",
        "wyslifestyle.com",
        "krishnaallplastic.com",
        "tlabglobal.com",
        "amitsharma.net",
        "planeteducation.info",
        "thechakorshop.com",
        "tickles.in",
        "viit-india.com",
        "creedhosting.com",
        "heynior.com",
        "indigoplus.in",
        "greenobazaar.com",
        "getxoog.com",
        "almightycs.com",
        "vdcstore.com",
        "cotandcandy.com",
        "resin24.com",
        "anana.co.in",
        "dataempires.co.in",
        "mandora.in",
        "buyboxonline.in",
        "xcluso.in",
        "geekmindz.com",
        "ymmbeta.myshopify.com",
        "uberurban.in",
        "cranesuperstore.com",
        "oowomaniya.com",
        "itsnuu.com",
        "label-s4u.com",
        "aryandreamholidays.com",
        "wowxop.com",
        "taanabaanabysapna.com",
        "parsanawellness.com",
        "stanmarkwellness.com",
        "solsons.com",
        "successinfotech.com",
        "volgaagency.com",
        "ranganjali.com",
        "bhastrabags.com",
        "dolphinapp.myshopify.com",
        "throttleart.com",
        "magmary.in",
        "thetravelworld.net.in",
        "bilnathhealthcare.com",
        "themedfa.com",
        "eonicpedals.com",
        "dabasorganic.com",
        "astrogurudeepakjain.com",
        "vittconsultant.com",
        "bioteknika.co.in",
        "prishie.com",
        "sattvishtik.com",
        "mavanidigital.com",
        "npluspro.com",
        "gunthanchhotu.com",
        "pestntrol.com",
        "styleemart.com",
        "xovakstudio.com",
        "mayfairaestheticsurgery.com",
        "padmahastacreations.com",
        "redspydetective.com",
        "kixcosmetics.com",
        "saddafashion.com",
        "neckedjeans.com",
        "trendystyleofficial.com",
        "cyphon.in",
        "thegoldentheory.com",
        "onelook.in",
        "crispcarnival.in",
        "kastham.com",
        "tetradeal.com",
        "paramparaorganic.com",
        "dafstudio.in",
        "skelott.com",
        "apexlight.in",
        "mybeautybazaar.com",
        "jankiimpex.com",
        "plantcare.co.in",
        "erpharbor.com",
        "jamuni.design",
        "greenworth.co.in",
        "pvcpipebellingmachine.com",
        "pixobots.com",
        "magebees.com",
        "aloxe.in",
        "wappnet.com",
        "meracacs.com",
        "samerth.org",
        "pleasurejunction.com",
        "syga.in",
        "risitahomelinen.com",
        "kcotn.in",
        "haikooethnic.com",
        "vitaminkash.com",
        "bondwellortho.com",
        "thecurateam.com",
        "garmium.com",
        "virat-group.com",
        "stitchmaninc.com",
        "girirajagarbatti.com",
        "glimayurveda.com",
        "manpras.com",
        "d9qdd6ey7o7ay.cloudfront.net",
        "yutibooks.com",
        "tansoracquets.com",
        "korbeauty.com",
        "shopify-monks.myshopify.com",
        "khodiyarcorporation.com",
        "tiaratrendz.com",
        "epotag.com",
        "frenchbonkers.com",
        "vinayaksilver.co.in",
        "meltnmold.co",
        "plantoart.com",
        "nevilpharma.com",
        "notrocketscience.in",
        "yashitechnoviz.com",
        "ebuzzsolution.com",
        "theanjoycompany.com",
        "buyonlinepc.com",
        "tinycrawl.com",
        "kalamdesign.com",
        "lugai.in",
        "freedworld.in",
        "owletail.shop",
        "thebodybucket.com",
        "xmxinfosoft.com",
        "myfantasylist.com",
        "aadarshhydropneumatics.com",
        "aumentoinfoway.com",
        "kamaleng.com",
        "saladfusion.in",
        "mydesimall.store",
        "gamebullz.com",
        "etsley.com",
        "shriyasilver.com",
        "ostilos.com",
        "samandmi.com",
        "ogbeauty.in",
        "incredereservices.com",
        "kamikubi.com",
        "technoadviser.com",
        "swingitservices.com",
        "natureocare.com",
        "healthyfuture.in",
        "memoriesofthearth.in",
        "gloweeorganics.com",
        "inkpresson.com",
        "shauree.in",
        "procequip.com",
        "uniquebusinessmarketer.com",
        "nutrileague.com",
        "getybo.com",
        "perfumex.in",
        "vensaa.com",
        "hhrotaryjoint.com",
        "hirenads.com",
        "satvajr.com",
        "thecreativeartisans.com",
        "vitabowl.in",
        "1bytwo.com",
        "bluedest.com",
        "rakhdi.com",
        "eximintell.com",
        "dryfruitbox.com",
        "magecoders.com",
        "dnsoftyengineering.com",
        "thewardrobefactory.com",
        "rajasthanjewellers.in",
        "berrica.com",
        "barbar.co.in",
        "tebho.com",
        "fusionevent.in",
        "unitechsolutionsindia.in",
        "artechfurniture.com",
        "eventsbyth.com",
        "ohsugar.in",
        "botspotinfoware.com",
        "betalafragrance.com",
        "ezcure.io",
        "builtsports.co.in",
        "dynamic-methods.com",
        "xeniks.com",
        "hcrayurveda.com",
        "parandish.com",
        "belliskey.com",
        "womink.com",
        "thecrockerycollection.com",
        "ideabaaz.in",
        "greencanes.in",
        "fluffytails.in",
        "jumbowafers.com",
        "mediskin.care",
        "maenterprise.in",
        "mediasolace.in",
        "dynamiceng.co.in",
        "heyshopper.in",
        "glareahealthcare.com",
        "thecurvves.com",
        "heeva.in",
        "mlm4india.com",
        "csr762.com",
        "ethnoroots.com",
        "ogonuts.com",
        "redorchid.in",
        "aavidtechnologies.com",
        "klaxonhomes.com",
        "braincrewapps.com",
        "catterton.in",
        "dreamcloset.co.in",
        "strivedigitals.com",
        "crochetbyprachi.com",
        "atozbazaar.in",
        "salmaans.in",
        "mohlifestyle.com",
        "balajinaturocares.com",
        "ittiho.com",
        "kakojee.com",
        "qhtmeds.com",
        "heritagepatola.com",
        "serverpartsindia.com",
        "dodibaksa.com",
        "jinalresinstudio.com",
        "passionatebrains.com",
        "product-shop.myshopify.com",
        "rangbyrajvi.com",
        "technocrackers.com",
        "magpiebooks.in",
        "karishmashahdesign.com",
        "rachaita.com",
        "snapkarts.shop",
        "reindeermachinery.in",
        "pioneerwebsystem.com",
        "keyurdudhat.in",
        "mstore-176.myshopify.com",
        "kalpeshastroservices.com",
        "flowers4ahmedabad.com",
        "itzoutsourcingfirm.com",
        "sapphirepartyplot.com",
        "globentis.com",
        "estorebird.com",
        "reliabletools.in",
        "grabcurio.com",
        "treeartinc.in",
        "navigatecommerce.com",
        "enzeo.in",
        "bumblebeebabywear.com",
        "cutieandboo.com",
        "cgfreejob.com",
        "peoplejewl.in",
        "indiasfashionstore.com",
        "aneleone.com",
        "3dstreet.in",
        "chimpaaanzee.com",
        "rototechindia.com",
        "surajsteelmet.com",
        "upteams.com",
        "bynirjari.com",
        "axisschoolofanimation.com",
        "optticshell.com",
        "wheymill.com",
        "foliumpura.com",
        "imagicsolution.in",
        "suparshavstudio.in",
        "thh.world",
        "manandanibjp.in",
        "b2bbox.in",
        "longene.co.in",
        "ouranostech.com",
        "mahavirengimach.com",
        "popularinfosys.com",
        "avancephyto.com",
        "apptestcorewix.myshopify.com",
        "acnf.in",
        "houseofpoetry.in",
        "bytesigner.in",
        "1rupiya.in",
        "sweetraga.com",
        "tepskart.in",
        "shreejigroup.info",
        "nandiniorganic.com",
        "hnathleisure.com",
        "arpanabhuwania.com",
        "trunkworksgames.in",
        "gramya.store",
        "shopaimraa.com",
        "taffrih.com",
        "pvcpipesocketingmachine.com",
        "elevatecbd.in",
        "artuzzii.com",
        "kookumber.in",
        "zaniee.com",
        "organicssite.com",
        "shopwithsans.com",
        "trushop.co.in",
        "metrocardagency.com",
        "easyshops.co.in",
        "earthaura.in",
        "thearomaplanet.com",
        "hermosajewels.in",
        "makeithome.in",
        "streetbeast.in",
        "puffiyana.com",
        "battlecry.in",
        "houseofmohini.com",
        "sockscarving.in",
        "maysixty.com",
        "baazmania.com",
        "menverse.in",
        "sveltecouture.in",
        "drifrutz.com",
        "5thanfold.com",
        "vedalay.in",
        "jvminfotech.com",
        "girirajdhoop.com",
        "narmees.com",
        "kansyam.com",
        "theappideas.in",
        "thewalloffaith.com",
        "woodiesland.com",
        "rudhvay.com",
        "ambarlyn.com",
        "kalpanascreations.in",
        "bajarangkitchen.com",
        "webbuyer.in",
        "clickitpictures.com",
        "isrcit.com",
        "krithaa.com",
        "mhplindia.com",
        "thelightship.org",
        "azula.studio",
        "parthjethva.store",
        "unlockmytrip.com",
        "satiatewater.com",
        "scramble.co.in",
        "obdushop.com",
        "ckimpharma.com",
        "parfumlab.shop",
        "navsarjan.in",
        "flits-plus.getflits.com",
        "futboltasticstore.in",
        "hkonlinemart.com",
        "ahmedabadads.com",
        "toolboxy.in",
        "sunnymachineries.com",
        "crystalhygiene.in",
        "trumaxsupplement.com",
        "supermemart.com",
        "motionmarketing.in",
        "hunger-x.com",
        "syink.in",
        "minaturewellness.com",
        "tohfa4u.com",
        "vishwaoffice.com",
        "sigmasolve.in",
        "outprfm.com",
        "anamikaranpura.com",
        "essentias.shop",
        "f2fshopee.com",
        "avelinejewels.com",
        "phoenixetc.com",
        "gadex.in",
        "hiqpic.in",
        "globalekarts.com",
        "necessentials.in",
        "thecongo.in",
        "futuresage.in",
        "finekida.com",
        "pluginsdemo.thedotstore.com",
        "thechocobite.com",
        "surilimukhwas.com",
        "luna.diamonds",
        "convertwcopy.com",
        "keramikcarcare.com",
        "monkeytrip.in",
        "i-buy.in",
        "karakiorigins.com",
        "happygadget.in",
        "easybuy1989.com",
        "themaltedstore.com",
        "luxejewelsbysamaira.com",
        "phinaturals.in",
        "priteshmodi.com",
        "fankaarii.com",
        "wepdemo1.myshopify.com",
        "seeeasy.shop",
        "rellifebuy.com",
        "solebae.co",
        "lailyo.in",
        "nobekafashion.com",
        "primeproductss.online",
        "emedhouse.com",
        "onceinamonth.com",
        "vickyfusionfinds.info",
        "trendly.co.in",
        "tagandshop.com",
        "eternalitems.com",
        "beelinecosmetics.com",
        "cyperx.in",
        "reshammbyrasshmi.com",
        "favouriteproducts.shop",
        "vendorclout.in",
        "lahayati.com",
        "sacman.shop",
        "basicshaat.com",
        "auraoutfit.in",
        "mojas.in",
        "etrendycart.store",
        "royalscent.in",
        "silverfoxind.com",
        "aonesolaroad.com",
        "grabby.in",
        "looomvogue.shop",
        "thehomeessentials.in",
        "bulbulfashions.com",
        "zerocutclothing.com",
        "kidsswear.in",
        "gynoglow.com",
        "testapst.myshopify.com",
        "sankalpstore.in",
        "paribindu.com",
        "hemveda.in",
        "clickbasket.in",
        "airho.in",
        "flixs.in",
        "sanj123123.myshopify.com",
        "madhavas.org",
        "neaksfashion.shop",
        "homeshop9.com",
        "labelmeera.com",
        "only-home.in",
        "airwave.fit",
        "foryourshop.in",
        "kathasilver.com",
        "vivaboots.in",
        "eatmagicmasala.com",
        "claymistry.in",
        "localdealstore.shop",
        "savvyzonelive.store",
        "thedmrbites.in",
        "spoils.in",
        "kiickas.com",
        "ubaba.store",
        "vtechnxtgenretails.com",
        "fabriconnects.com",
        "tatvagreens.in",
        "bharatpowerenergy.com",
        "rose-iya.com",
        "kartgraffy.com",
        "soulfulcure.com",
        "toylegends.fun",
        "issori.com",
        "kickdrops.in",
        "theblissy.top",
        "trendshops.in",
        "thehometrolley.com",
        "bluestain.in",
        "hiramanilights.com",
        "perfumeholic.in",
        "mossconcept.in",
        "divaearrings.in",
        "genericbharat.com",
        "texelinternational.com",
        "megluspharma.com",
        "mamabhana.com",
        "numann.in",
        "sunisa.shop",
        "kawaishop.in",
        "famous-kurtis.shop",
        "tryop.in",
        "satrangifashion.com",
        "bijoi.in",
        "yellowiris.com",
        "skynitedesign.com",
        "davaae.in",
        "nammaaushadi.com",
        "klassykurt.in",
        "sockscarving.co.in",
        "univa.in",
        "nuflameindia.com",
        "hylectrix.com",
        "veshfashions.com",
        "gardeningsolution.in",
        "theraylabel.com",
        "flipkartbag.com",
        "idabeauty.in",
        "thevintagehub.in",
        "zedancosmetics.com",
        "chandamamagifts.com",
        "pagalworldh.com",
        "alkat.in",
        "quickflipfinds.com",
        "nuhomes.in",
        "pernitty.com",
        "zovene.in",
        "teasemyvelvetbody.com",
        "kalanidhi.co.in",
        "raasil.in",
        "hirendra.myshopify.com",
        "almero.in",
        "alldesigncreation.com",
        "beingyogi.in",
        "lexolex.com",
        "bellavitapizza.in",
        "parfumlab.co",
        "threadilo.com",
        "wellness-wagon.shop",
        "tanushop.in",
        "jenishinfra.in",
        "momatos.in",
        "plantseindia.com",
        "freespiritsfashion.co.in",
        "namchinthedesignerstudio.com",
        "b4byk.com",
        "techsamundra.com",
        "blndwater.com",
        "magegadgets.com",
        "quickrepairservice.in",
        "craftise.co",
        "truveli.in",
        "coldexsodafountain.com",
        "jhakaasitem.com",
        "macedoine.in",
        "altfragrance.in",
        "talkfreely.co",
        "maxmeglobal.com",
        "shopbyte.in",
        "pixorcewebdesign.com",
        "51kgrowthhub.com",
        "etacontemporary.com",
        "roadconstructionmachineries.com",
        "okgreens.in",
        "quencekart.in",
        "wedberry.store",
        "fynakaa.com",
        "credibleshoemart.com",
        "hadvanis.com",
        "fasoonindia.com",
        "lacely.in",
        "kananplast.com",
        "tamraabespoke.com",
        "peonylifestyle.in",
        "montecarloexclusiveshowroomahmedabad.com",
        "karkare.in",
        "twelvepotterystudio.com",
        "taankjhank.com",
        "merakibeauty.in",
        "hmmbiz.com",
        "njoyindia.com",
        "biometricsmachine.com",
        "cerra.in",
        "edupme.com",
        "gheewala.in",
        "ketzealoverseas.com",
        "phulawall.com",
        "synobiz.com",
        "fashnetic.in",
        "aagneyaenterprises.com",
        "azetro.com",
        "eryinyes.com",
        "theneohomes.com",
        "swarnaratna.com",
        "ahmedabadtechnolabs.com",
        "rajsoftech.com",
        "powerg.in",
        "steritechnofab.com",
        "navyaindia.co.in",
        "bemodern.in",
        "kaseenda.com",
        "badrealambukhari.org",
        "shreeshankarcreation.in",
        "krupainfoservices.com",
        "niveusfashion.com",
        "creations007.com",
        "nidawellness.com",
        "casetonics.com",
        "revisol.in",
        "tittlifashionstore.com",
        "econice.in",
        "nishistore.com",
        "artmeupbykinmil.com",
        "purplesoul.in",
        "epiceats.in",
        "embroidery4u.in",
        "sujaladhia.com",
        "aarviflourmill.com",
        "epsoftech.com",
        "storearmy.com",
        "luciferandhesper.com",
        "swanky-india.com",
        "happishades.com",
        "elegity.com",
        "madhurstore.com",
        "shreeomrudraksh.com",
        "epitomeitsolutions.com",
        "clientsnow.co.in",
        "houseofshailja.com",
        "zwankee.com",
        "kartcorner.shop",
        "easybuyer.in",
        "thatprettybubble.com",
        "virasatpatola.com",
        "kraftifystore.com",
        "vervikherofficial.com",
        "sokoliving.in",
        "cookezybox.com",
        "themonkeydeals.com",
        "harrozworld.com",
        "decoremodern.com",
        "activesclub.com",
        "witlamps.com",
        "theurbanthings.in",
        "f4mart.com",
        "supplies-textile-2.myshopify.com",
        "mrgardenr.com",
        "dinkywhee.com",
        "xanderinc.io",
        "haiskn.com",
        "arihantinfosoft.in",
        "euroxoart.com",
        "evantastore.com",
        "beholistic.in",
        "tsakuclothing.com",
        "ojolens.in",
        "medipik.com",
        "bakeadiem.in",
        "kalakaribyrhuju.com",
        "sanyoginfosys.com",
        "harancapital.com",
        "ready2code.com",
        "milligantgolf.com",
        "mymedical24.com",
        "sahajherbals.com",
        "candevsolutions.com",
        "aksharenterprises.shop",
        "maheshblowers.com",
        "thekaleidos.com",
        "starliteweb.com",
        "saharamachine.com",
        "canvaskraft.in",
        "hkclothinghand.com",
        "demomagento2.appjetty.com",
        "theseahorse.in",
        "getough.in",
        "traininggurukul.com",
        "goldenshield.in",
        "junglelements.com",
        "koheva.com",
        "parfumlabs.in",
        "aumbrr.com",
        "setigbt.com",
        "zestard-shopify.myshopify.com",
        "drdelisho.com",
        "krocusboutique.com",
        "boostlife.shop",
        "mrugashi.com",
        "thegreencommerce.in",
        "nilamscloset.com",
        "krivfoods.com",
        "sheenachawlaart.com",
        "naturetroops.com",
        "futuristictechnologies.co.in",
        "casesafe.in",
        "gilden.in",
        "smart-buyer.co.in",
        "coverchamp.com",
        "westernfoxfashion.com",
        "tinytouch.in",
        "hazelnutessentials.com",
        "globalminaturewellness.com",
        "rajaselection.com",
        "blankrew.com",
        "editbykash.com",
        "drmahavirtadaiya.in",
        "wowzstore.com",
        "relyxresearch.in",
        "arknatural.com",
        "minlybites.com",
        "qluxlights.com",
        "kyore.in",
        "saigems.co.in",
        "ilarin.co.in",
        "444angels.in",
        "scoopywear.com",
        "dhaani.co",
        "hnwb2b.com",
        "sutirthayu.com",
        "mysattvalife.com",
        "meolaindia.com",
        "hosting1.in",
        "simbalian.org",
        "orgacia.com",
        "trendemart.in",
        "lootlo.online",
        "robblebox.com",
        "smitahandicraft.com",
        "ultrasonicspareparts.com",
        "heelsandfeelsindia.com",
        "swiftnectar.com",
        "teequila.in",
        "daughtersofsouth.com",
        "lifetec.in",
        "talkingwalls.in",
        "dreamdipdelight.com",
        "underfifteen.in",
        "elementenergy.co.in",
        "romanshakumar.com",
        "ekaanindia.com",
        "almashi.in",
        "shreenathastrologyandpooja.com",
        "littlebitofheaven.in",
        "whey91.com",
        "ethonique.com",
        "pasteldhaaga.com",
        "sanscrita.com",
        "arogyabharat.in",
        "naturified.com",
        "missandmrs.co.in",
        "hoobahoolabel.in",
        "andante.co.in",
        "ghanshyamenterprise.com",
        "fabgadget.in",
        "nutrabreeze.com",
        "shopzykart.in",
        "pareshkapuriya.com",
        "systechsolutions.co",
        "indienicheartisanal.com",
        "educationworld.co.in",
        "tahska.com",
        "kanikadesignstudio.com",
        "confimen.in",
        "labledit.com",
        "freshpetz.in",
        "blaconyx.com",
        "wrappedjoy.in",
        "fhmstores.com",
        "clovurbanestudio.com",
        "arakperfume.com",
        "bhaaav.com",
        "trendiwish.com",
        "houseofbarkha.com",
        "dawasetu.co.in",
        "napsomnia.com",
        "emma-london.com",
        "brexhealth.com",
        "anubhavipandit.com",
        "theofferskart.com",
        "nuvijewels.com",
        "battercap11.com",
        "orangeoralcare.com",
        "thekansha.com",
        "shrutratnakar.org",
        "sigmacraft.in",
        "vastralipi.com",
        "tarakvora.in",
        "becoist.com",
        "rathodandcloths.shop",
        "outlookbyriganthony.com",
        "plantin.in",
        "tltnaturals.com",
        "heartysstop.com",
        "omaho.in",
        "zestwebsolutions.com",
        "accentstudio.se",
        "zadar.co.in",
        "ipowerhub.in",
        "zestnzingfoods.com",
        "namyara.com",
        "artwork55.co.in",
        "thesignaturepro.com",
        "beastclothing.co.in",
        "parfum-lab.in",
        "braveandbeauti.com",
        "vastites.com",
        "vanaama.in",
        "niftians.co.in",
        "dopstop.in",
        "lakayaindia.com",
        "achiraindia.com",
        "fotolelo.com",
        "rhpso.com",
        "kezaliherbals.com",
        "theunrivaled.in",
        "aaviansnature.com",
        "rupalibyswagataborah.com",
        "resinartology.in",
        "dot7.in",
        "vrajhomedecor.com",
        "velbeon.com",
        "iani.in",
        "waawaawooo.com",
        "onehike.in",
        "rigicglobalsolutions.com",
        "inkfusion.co",
        "infinityshoppy.com",
        "aksharpaperagency.com",
        "epoxyresins.in",
        "modernmarket.in",
        "zordosh.com",
        "helps.foundation",
        "mylifey.in",
        "favouritecomputers.com",
        "itzzel.com",
        "intimacyhub.in",
        "begetnectar.com",
        "ultrasonicweldings.net",
        "spurtric.com",
        "fresherbal-solutions.com",
        "purrcolatecoffeeco.in",
        "petalpurityshop.com",
        "elenbyjr.com",
        "sagashop.in",
        "indiansummercreatives.in",
        "meentheartofthread.com",
        "nidhihalani.in",
        "webcodexworld.com",
        "checklist.co.in",
        "umiyaprinters.com",
        "advitiyabynehadewan.com",
        "navsyaa.com",
        "dianiworld.com",
        "shaarav.in",
        "orla.in",
        "funkitup.in",
        "hemalidigital.com",
        "elsnerinc.com",
        "tanishkaasarees.com",
        "vibingshakti.com",
        "trendyswift.store",
        "techlokye.com",
        "houseoftma.com",
        "howtocollege.in",
        "tdsallinonestore.in",
        "skillup.org.in",
        "luire.in",
        "propeptides.in",
        "naoz.in",
        "nishstore.com",
        "sigma-store-2.myshopify.com",
        "huestory.in",
        "reeplo.com",
        "buyinstrument.shop",
        "aakardigital.co.in",
        "dspwholeseller.in",
        "kidsage.co.in",
        "cookienuts.in",
        "ottplateform.shop",
        "brahmanidresses.com",
        "bleupetrol.in",
        "alivensleek.in",
        "printinahmedabad.in",
        "homeshoper.in",
        "cactusgoodness.com",
        "kratosfitnessandsupplements.com",
        "pagalworlid.com",
        "pbmage.com",
        "zymeck.com",
        "buenotee.com",
        "vedavital.shop",
        "soloclub.in",
        "bozarro.com",
        "meramotivation.in",
        "devamgroup.in",
        "gloposnet.in",
        "ricecake.in",
        "stockbay.in",
        "nisargahir.net",
        "sparkcoders.co.in",
        "lawbooksin.com",
        "akiva.online",
        "veinasmachineindia.com",
        "glow-skin.in",
        "breathabless.com",
        "yelogift.com",
        "testmyapi.myshopify.com",
        "thebuzzcart.shop",
        "qoptotechnologies.in",
        "abfs.in",
        "beerjeans.in",
        "happy2shop.in",
        "tapzy.in",
        "viraasatthelegacy.com",
        "karikala.co.in",
        "anandacbseschool.com",
        "mordantbs.com",
        "bnbkidsstore.com",
        "asanchifashion.com",
        "balshishu.com",
        "fecundtechno.com",
        "devhen.in",
        "unlistedmitra.com",
        "indichic.store",
        "castorskart.com",
        "troomskids.com",
        "worldwebinfotech.in",
        "kidsagecoding.in",
        "dhanyaconsultancy.in",
        "prosageeducore.com",
        "mmdretail.com",
        "snishsignature.com",
        "world4help.com",
        "kishorify.com",
        "jiyucreation.com",
        "binarycodeservices.com",
        "aaravya.com",
        "muslimstore.in",
        "shop.symphonylimited.com",
        "ketanapp.myshopify.com",
        "in.ilemjapan.com",
        "ymms.myshopify.com",
        "shop.arcedior.com",
        "ebizfiling.linker.store",
        "source-textiles.myshopify.com",
        "trimmer.beardo.in",
        "shop.cyclone.org.in",
        "checkout-in.biosil.beauty",
        "store.delwishealthcare.com",
        "standalonem2.brushyourideas.com",
        "byi-woocommerce.brushyourideas.com",
        "shop.harekrishnamandir.org",
        "shop.lineomatic.com",
        "shop.virgouap.com",
        "investments.pacificacompanies.co.in",
        "amd.deodap.com",
        "store.amrutenergy.com",
        "evincedemoo.myshopify.com",
        "demostore-configurator.brushyourideas.com",
        "card.brushyourideas.com",
        "sticky-add-to-cart.myshopify.com",
        "adastl-1.myshopify.com",
        "akashdit.myshopify.com",
        "checkout.vedalay.in",
        "dentalimplant.agravat.com",
        "easy2-buy-shop.myshopify.com",
        "trulavi-shop.myshopify.com",
        "jdiar.myshopify.com",
        "smit-dudhat.myshopify.com",
        "shop.hofindia.com",
        "shop.cubithealthcare.net",
        "docs.appjetty.com",
        "magemob.appjetty.com",
        "eparcelm2.appjetty.com",
        "umaswadam.vishvumiyafoundation.org",
        "fabulivahd.myshopify.com",
        "truerevoindia.myshopify.com",
        "uat-business-f2fmart.myshopify.com",
        "tfunnyfashion.myshopify.com",
        "bduck-template.myshopify.com",
        "moskitrapstore.myshopify.com",
        "ethnoroots.myshopify.com",
        "otrixindia.myshopify.com",
        "tsm-retailer.myshopify.com",
        "heywomn.myshopify.com",
        "v2hweb.myshopify.com",
        "ludic-stage.myshopify.com",
        "demoshopifyapp.myshopify.com",
        "rchintan7.myshopify.com",
        "deeptest123.myshopify.com",
        "metiz-tier-price.myshopify.com",
        "mrdnk-3.myshopify.com",
        "efashiony.myshopify.com",
        "clothcolletion.myshopify.com",
        "officialshopifypartner.myshopify.com",
        "jaydip-kanasagra.myshopify.com",
        "flickkon2.myshopify.com",
        "bozzuto.myshopify.com",
        "invoicehero1.myshopify.com",
        "radrealm.myshopify.com",
        "demo-store-126.myshopify.com",
        "zankhana-bhalani.myshopify.com",
        "vivahcenter.myshopify.com",
        "iampyus.myshopify.com",
        "gargdimple27.myshopify.com",
        "creativecraftonline.myshopify.com",
        "wp-ravi.myshopify.com",
        "online-sellshopworld.myshopify.com",
        "estore-39.myshopify.com",
        "marion-pumpkinposters.myshopify.com",
        "ensigh.myshopify.com",
        "a20shop.myshopify.com",
        "lucentinnovationtest3.myshopify.com",
        "amp-onboarding.myshopify.com",
        "halfticket-2.myshopify.com",
        "rajeshacs.myshopify.com",
        "batt-savl.myshopify.com",
        "dakshal.myshopify.com",
        "ruff-tuff.myshopify.com",
        "mask-availability.myshopify.com",
        "onlinestore-20.myshopify.com",
        "dollapee1.myshopify.com",
        "store-for-ron-v.myshopify.com",
        "digikam.myshopify.com",
        "tannesr-goods.myshopify.com",
        "mahesh-57.myshopify.com",
        "front-end-assignment.myshopify.com",
        "jalpa3.myshopify.com",
        "essence-theme-store.myshopify.com",
        "development-for-ymm.myshopify.com",
        "webosphere-2.myshopify.com",
        "sikarwarajay.myshopify.com",
        "littlebabycarestore.myshopify.com",
        "snippetbucket-2.myshopify.com",
        "fashnn.myshopify.com",
        "shop24x7-3.myshopify.com",
        "sachin-order-tagger.myshopify.com",
        "fce646.myshopify.com",
        "trendythreadsbyd.myshopify.com",
        "akash-narwariya-ebiztrait.myshopify.com",
        "dhaivatdave-2.myshopify.com",
        "demo-shop-47.myshopify.com",
        "bytes-3.myshopify.com",
        "esb-first.myshopify.com",
        "raisingcart.myshopify.com",
        "mspstore-2.myshopify.com",
        "rkvarma.myshopify.com",
        "nikita-29.myshopify.com",
        "arhive.myshopify.com",
        "nirma.myshopify.com",
        "eshop-textiles.myshopify.com",
        "mandywu.myshopify.com",
        "closeoutkitchens.myshopify.com",
        "onlinestoretest-2.myshopify.com",
        "princess-by-renee.myshopify.com",
        "wepdemo3.myshopify.com",
        "radhesh.myshopify.com",
        "skinfo.myshopify.com",
        "tejas-nadpara.myshopify.com",
        "wp-shailesh.myshopify.com",
        "kandarp-onlinestore.myshopify.com",
        "weddingcardhub.myshopify.com",
        "last-login.myshopify.com",
        "rameshshop.myshopify.com",
        "maulikeq.myshopify.com",
        "mystyle90999.myshopify.com",
        "shraddha65.myshopify.com",
        "biztech-app-development.myshopify.com",
        "digitusstore.myshopify.com",
        "laases.myshopify.com",
        "etatvasoft.myshopify.com",
        "gkstore2024.myshopify.com",
        "little-pet-houses.myshopify.com",
        "cyblancestore.myshopify.com",
        "indian-digital-goods.myshopify.com",
        "jassproteststore.myshopify.com",
        "darshana-bhuva.myshopify.com",
        "wepdemo11.myshopify.com",
        "kbakery.myshopify.com",
        "ommune.myshopify.com",
        "bigbazzar-2.myshopify.com",
        "metizquiz.myshopify.com",
        "sold-stock-bar.myshopify.com",
        "wp-lalit.myshopify.com",
        "dharti-bhimani.myshopify.com",
        "varient.myshopify.com",
        "vipulacc.myshopify.com",
        "my-new-tseting-store.myshopify.com",
        "sachin-collect.myshopify.com",
        "dollapee.myshopify.com",
        "testreturnorder.myshopify.com",
        "veer-sales-ahd.myshopify.com",
        "moblicom.myshopify.com",
        "restor-2.myshopify.com",
        "brand-you.myshopify.com",
        "last-2.myshopify.com",
        "furnituretatva.myshopify.com",
        "kavisha123.myshopify.com",
        "searching-4.myshopify.com",
        "expertbison.myshopify.com",
        "b2c-1073.myshopify.com",
        "bootstrap-co-in.myshopify.com",
        "sofa-bed-3.myshopify.com",
        "giftsbyaangi.myshopify.com",
        "hapitizerindia.myshopify.com",
        "abcapp.myshopify.com",
        "tatvajewels.myshopify.com",
        "infinite-product-options-developer.myshopify.com",
        "demo-upsell.myshopify.com",
        "devesh-arya.myshopify.com",
        "pakkaamdavadi-2.myshopify.com",
        "sharetogetdiscount.myshopify.com",
        "indiansarees-2.myshopify.com",
        "experimentalstore12.myshopify.com",
        "thisisridiculousstore.myshopify.com",
        "piggyparcels.myshopify.com",
        "jadejatest1.myshopify.com",
        "tmsjp.myshopify.com",
        "mytestac.myshopify.com",
        "stampstockist.myshopify.com",
        "simform-solutions.myshopify.com",
        "bhavik-1.myshopify.com",
        "corewix.myshopify.com",
        "demo-shop-30.myshopify.com",
        "foody-pets.myshopify.com",
        "envelope-app.myshopify.com",
        "ultrapure-nutrition.myshopify.com",
        "hupp-ajax-search.myshopify.com",
        "grow-ahead.myshopify.com",
        "stormylearning.myshopify.com",
        "my-new-shop-7.myshopify.com",
        "zoobacarts.myshopify.com",
        "demo-project4.myshopify.com",
        "flits-support-workplace.myshopify.com",
        "varien2.myshopify.com",
        "advance-faq.myshopify.com",
        "onlinexyz.myshopify.com",
        "salewaveshop.myshopify.com",
        "age-verification-pop-up.myshopify.com",
        "omicron-7032.myshopify.com",
        "loyal-web-solution.myshopify.com",
        "dhwanizwt.myshopify.com",
        "bharatgunani-myshopify-com.myshopify.com",
        "modernwear-dev2.myshopify.com",
        "shopify-coupon-code.myshopify.com",
        "wepdemo4.myshopify.com",
        "local-vdb-app-store.myshopify.com",
        "jodedemo1.myshopify.com",
        "wepdemo9.myshopify.com",
        "vveks-shop.myshopify.com",
        "pricemon.myshopify.com",
        "huptechgift.myshopify.com",
        "esb-second.myshopify.com",
        "sigma40-2.myshopify.com",
        "snippetbucket.myshopify.com",
        "shopify-tech-monks.myshopify.com",
        "pipl-first-store.myshopify.com",
        "sales-812.myshopify.com",
        "debutthem.myshopify.com",
        "mlveda-sagar.myshopify.com",
        "uincases.myshopify.com",
        "esb-third.myshopify.com",
        "new-store-22.myshopify.com",
        "agile-4.myshopify.com",
        "shadescool.myshopify.com",
        "darshify11.myshopify.com",
        "wp-dinesh.myshopify.com",
        "local2vocal.myshopify.com",
        "mod-inventory.myshopify.com",
        "avidbrio.myshopify.com",
        "new-apt1.myshopify.com",
        "fashion-week-sale.myshopify.com",
        "jcaspdevelopment.myshopify.com",
        "related-products-and-blogs.myshopify.com",
        "brands4allcopy.myshopify.com",
        "printondoc.myshopify.com",
        "webosphere-3.myshopify.com",
        "dolphin-web-solution.myshopify.com",
        "wepdemo8.myshopify.com",
        "easywebapps.myshopify.com",
        "ikhedut.company.site",
        "sid-tech.myshopify.com",
        "beautiesluv.myshopify.com",
        "neal-7.myshopify.com",
        "cwsgold.myshopify.com",
        "ampfire.myshopify.com",
        "climbingworld-1.myshopify.com",
        "joy-digital-shoppe.myshopify.com",
        "indianic-2.myshopify.com",
        "indiansaree-2.myshopify.com",
        "shop-576.myshopify.com",
        "faithxculture.myshopify.com",
        "f45a52-2c.myshopify.com",
        "testcorewix.myshopify.com",
        "zemity.myshopify.com",
        "lucentinnovationtest1.myshopify.com",
        "shopalbert105.myshopify.com",
        "olgreens.com",
        "rainartsacademy.com",
        "wownandi.in",
        "threadsbybhavi.com",
        "vitanlife.myshopify.com",
    ]
    # Add your URLs here

    # You can also load URLs from a file
    def load_urls_from_file(filename: str) -> List[str]:
        """Load URLs from a text file (one URL per line)."""
        try:
            with open(filename, "r") as f:
                urls = [line.strip() for line in f if line.strip()]
            return urls
        except FileNotFoundError:
            logger.error(f"File {filename} not found")
            return []

    # Uncomment to load from file:
    # urls = load_urls_from_file("urls.txt")

    if not urls:
        print(
            "No URLs to scrape. Please add URLs to the 'urls' list or create a 'urls.txt' file."
        )
        return

    # Configure scraper settings
    scraper_config = {
        "max_concurrent": 5,  # Number of simultaneous requests
        "timeout": 30,  # Request timeout in seconds
        "delay_between_requests": 1,  # Delay between requests (be respectful)
    }

    # Run the scraper
    async with SmartEmailScraper(**scraper_config) as scraper:
        results = await scraper.scrape_urls(urls)

        # Print summary
        scraper.print_summary(results)

        # Save results
        scraper.save_results_to_csv(results, "email_results.csv")
        scraper.save_results_to_json(results, "email_results.json")


if __name__ == "__main__":
    # Run the scraper
    asyncio.run(main())
